// <auto-generated />
namespace Project.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class altercollun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altercollun));
        
        string IMigrationMetadata.Id
        {
            get { return "201803232052527_alter-collun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
